### ISSUE TITLE
What operating systems does it support?  (README doesn't say.)

### ISSUE THREAD

**Issue by kfogel** [akon47/ScreenRecorder#11]
The README doesn't say outright what operating systems this works with.  From the "Build" section, one can infer that Windows (but what versions of Windows?) is supported, but that's only an inference.  It would be good to just state in the README what the OS compatibility is.

Best regards,
-Karl

**Comment by akon47** [comment]
Oh! I didn't think of that part. Thank you for your opinion. I'll add some more. Thank you for your feedback.

**Comment by akon47** [comment]
Added system requirement section to readme file. Thank you!

**Comment by kfogel** [comment]
Thanks so much, @akon47!
