### ISSUE TITLE
Unable to record non-primary monitor

### ISSUE THREAD

**Issue by RyanBellPOST** [akon47/ScreenRecorder#12]
Screen recording only allows me to capture the content displayed on my primary monitor. I cannot select which monitor I would like to capture from.

**Comment by akon47** [comment]
Okay, I'll add that feature to the next version.

**Comment by akon47** [comment]
Added in version 1.0.7. Thank you.

![screenshot2_en](https://user-images.githubusercontent.com/49547202/131944613-481e5e56-02e6-41ba-b07b-b078babe3403.png)
