### ISSUE TITLE
Issue with Microsoft Visual C++ 2017-2019 Redistributable (x64)

### ISSUE THREAD

**Issue by chuongmep** [akon47/ScreenRecorder#13]
Hi,
I'm installed Microsoft Visual C++ 2017-2019 Redistributable (x64), wheather we have any update for fix that problem?
Any suggestions appreciated.
![image](https://user-images.githubusercontent.com/31106432/131939358-66f24d69-c96e-47b9-9c2f-cf6443383af4.png)

**Comment by akon47** [comment]
When I checked the latest version of the redistribution package, I found that the part to check the installation has changed.
Let's fix the next version to recognize the latest version of the redistribution package. Thank you so much for your feedback!

First of all, I'll attach the previous version of the redistribution package installation file that I have.
Sorry for the inconvenience.

[VC_redist.x64_14.29.30037.zip](https://github.com/akon47/ScreenRecorder/files/7102896/VC_redist.x64_14.29.30037.zip)

**Comment by chuongmep** [comment]
Can we skip this process check ?
![image](https://user-images.githubusercontent.com/31106432/131942309-9843e2bb-d6fb-4b58-b0d7-212b150fbdb3.png)

**Comment by akon47** [comment]
Please check after installing the pre-released version of 1.0.7. Thank you.

**Comment by chuongmep** [comment]
Same Problem, it not working for me with C++ 14.30

**Comment by akon47** [comment]
Let me check again.

**Comment by chuongmep** [comment]
I add some details for you to consider.Thanks you.
![image](https://user-images.githubusercontent.com/31106432/131950434-5fe272b6-511a-42bf-a8d4-19b910fb694f.png)

**Comment by akon47** [comment]
Eureka! It was version 2022. I didn't even think about it. Thank you for the information.
