### ISSUE TITLE
Microphone recording

### ISSUE THREAD

**Issue by sameer-coder** [akon47/ScreenRecorder#24]
Hey,

The tool is fantastic and does the job without any fuss. I was wondering if it is possible to record the audio from the microphone as well in zoom calls? Right now it only records other participants speaking.

Thanks

**Comment by akon47** [comment]
Yes, I'll add the microphone recording function to the next version. thanks

**Comment by akon47** [comment]
![image](https://user-images.githubusercontent.com/49547202/132880134-35cb73b5-1044-4880-8299-b9ba5b875384.png)

![image](https://user-images.githubusercontent.com/49547202/132880217-932bee5f-e81b-457d-9d28-d73cd17204dd.png)

Please check the 1.1.1 version.
Record the system default capture device.

**Comment by sameer-coder** [comment]
Tested. Works amazing 🎉 
Thank you for such a quick release!
