### ISSUE TITLE
Could we have ScreenRecorder on Scoop or Winget?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [akon47/ScreenRecorder#31]
* https://scoop.sh/
* https://github.com/microsoft/winget-cli

**Comment by akon47** [comment]
It's not available on Scoop and Winget, however I will consider adding this on Winget soon

**Comment by akon47** [comment]
A PR request has been made. When the review is complete, it will be registered.

[winget-pkgs PR](https://github.com/microsoft/winget-pkgs/pull/64350)
