### ISSUE TITLE
원격제어하면서 프로그램 사용방법

### ISSUE THREAD

**Issue by cutemanager** [akon47/ScreenRecorder#33]
안녕하세요.
제 pc 에서 유용하게 잘 쓰고 있어서 다른 pc 에도 써볼려고 하는데,
teamviewer나 다른 원격프로그램에서 조작할려고 하면
아래처럼 화면이 안보이더라구요.
원격하면서 조작할 수 있을까요?

![녹화프로그램](https://user-images.githubusercontent.com/51126573/148688388-4dc88072-d401-4f02-a602-31ad1d8b0412.png)

**Comment by akon47** [comment]
녹화시에 자기 자신은 녹화가 되지 않도록 하는 부분이 있는데, 원격 제어시에 자기 화면을 캡쳐해서 전송하는거라 원격 제어 프로그램에서도 캡쳐가 되지 않는 현상으로 보입니다. 
캡쳐가 되지 않도록 하는 부분을 따로 옵션으로 만들어 On/Off 가 가능하게 하거나 해야 할 것 같네요.

**Comment by akon47** [comment]
> 답변주셔서 감사합니다. 옵션으로 만들 수도 있군요. 프로그램도 가볍고 성능이 좋아서 잘 쓰고 있습니다 ^^ 혹시 다중 모니터 사용할 경우 1번 모니터만 녹화하게 되는걸까요?

프로그램 설정창의 우측 하단의 고급 설정 메뉴를 체크하시면 녹화 대상 부분에서 녹화 모니터 선택이 가능합니다.
![image](https://user-images.githubusercontent.com/49547202/154746278-72996e67-69a0-4e7e-8d21-c8f55aaa5fe5.png)

**Comment by akon47** [comment]
1.1.3 버전에서는 원격제어를 이용하여도 녹화 프로그램이 보이도록 수정하였습니다.

**Comment by cutemanager** [comment]
> 1.1.3 버전에서는 원격제어를 이용하여도 녹화 프로그램이 보이도록 수정하였습니다.

한결 편해져서 잘 사용하고 있습니다!
예전에 다중모니터 사용할 때 모니터 선택 녹화 관련해서 여쭤봤었는데 모니터 구분되지않고 2개 화면이 한번에 녹화할 순 없을까요? 사용자 지정방식도 한 모니터만 사용하도록 되있더라구요.
