### ISSUE TITLE
Huge noise

### ISSUE THREAD

**Issue by odorizzioficial** [akon47/ScreenRecorder#37]
Hi, great recorder, but it is giving a huge noise on Windows 10 21h2 with the fifine microphone, the other recorders do not happen, could you fix the problem

Vídeo Test: https://youtu.be/aUVxM42VB88

**Comment by akon47** [comment]
I would like to know the status of your audio settings for reproduction purposes.

![1](https://user-images.githubusercontent.com/49547202/192761076-874aa65e-b20a-4ba3-8584-628d59d715f7.png)
### or
![2](https://user-images.githubusercontent.com/49547202/192760998-43dd5918-1e0e-45d7-93c9-e6129696ff36.png)
fce.png)

**Comment by odorizzioficial** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/110546717/192868540-86bf1ada-786c-4a6d-9ebd-f060a0d91fac.png)

Hi, it is at 48000 hz, but only in your application does this happen, in others it does not.

**Comment by akon47** [comment]
I found this to happen in 144 fps recordings.
I've found a way to reproduce that problem, so I'll fix it.
Thanks for letting me know the problem.

**Comment by akon47** [comment]
Fixed in version 1.1.5. Please check. Thank you for your feedback.

**Comment by odorizzioficial** [comment]
> Fixado na versão 1.1.5. Por favor, verifique. Obrigado pelo seu feedback.

I fixed it, thank you so much <3, I will bring a video showing your software to my audience on my YouTube channel to help you, can I bring it?

**Comment by odorizzioficial** [comment]
> Fixado na versão 1.1.5. Por favor, verifique. Obrigado pelo seu feedback.

It worked, thank you so much <3, I will bring a video showing your software to my audience on my YouTube channel to help you, can I bring it?

My Channel: https://www.youtube.com/channel/UC4rSCAdhng0kzfXfLubGVuA/

One more suggestion, have the option to record audios on separate tracks:

System 1
Game 2 
Microphone 3 

 <3
