### ISSUE TITLE
Recorder wont open after first launch

### ISSUE THREAD

**Issue by NicciZar** [akon47/ScreenRecorder#42]
Whenever I recorded a session, closed the program and reopened it, the icon appears in taskbar but there is no GUI to be seen.

I always have to delete the config in %appdata% /Recorder folder so it works again.

**Comment by akon47** [comment]
Hello. I tried various methods to reproduce the phenomenon, but I couldn't reproduce it. Could you provide more detailed information about the situation? 😢

**Comment by NicciZar** [comment]
Thank you for checking this out.

Seems like its working again so I dont have to delete the settings file.

OS: Windows 10 Pro (Useraccount without Administrator rights)
Savepath was set to an external drive
