### ISSUE TITLE
Mouse Pointer Looks Wrong

### ISSUE THREAD

**Issue by ogre** [akon47/ScreenRecorder#9]
https://i.imgur.com/zC1wZKk.png

Mouse arrow looks wring in recorded video.
I have a custom icon for mouse pointer

**Comment by akon47** [comment]
Got it, will be revised in next version. Thank you for the feedback.

**Comment by akon47** [comment]
If possible, can you send me the mouse pointer icon you use or get a link to download it?

**Comment by ogre** [comment]
[arrow_mRED.zip](https://github.com/akon47/ScreenRecorder/files/7098710/arrow_mRED.zip)

**Comment by akon47** [comment]
thank you. I'll check

**Comment by akon47** [comment]
Fixed in version 1.0.6. Please check. Thank you for your feedback.
